name: AspServiceBusEmulator
services:

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis-stack
    ports:
      - "6388:6379"
    environment:
      - REDIS_PASSWORD=yourpassword

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - "8088:5540"  # Exposing RedisInsight UI
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6388
      - REDIS_PASSWORD=yourpassword
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27020:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
      - MONGO_INITDB_DATABASE=mydatabase

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8085:8081"  # Exposing Mongo Express UI
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpassword
      - ME_CONFIG_MONGODB_URL=mongodb://root:rootpassword@mongodb:27017/
    restart: always


  emulator:
    container_name: "servicebus-emulator-testing"
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    volumes:
      - "${CONFIG_PATH}:/ServiceBus_Emulator/ConfigFiles/Config.json"
    ports:
      - "5672:5672"
    environment:
      SQL_SERVER: sqledge  
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: ${ACCEPT_EULA}
    depends_on:
      - sqledge
    networks:
      sb-emulator:
        aliases:
          - "sb-emulator"
  sqledge:
        container_name: "sqledge-testing"
        image: "mcr.microsoft.com/azure-sql-edge:latest"
        networks:
          sb-emulator:
            aliases:
              - "sqledge"
        environment:
          ACCEPT_EULA: ${ACCEPT_EULA}
          MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}

networks:
  sb-emulator:


volumes:
  mongodb_data: